### ISSUE TITLE
Grab JMS Headers

### ISSUE THREAD

**Issue by AayushaY** [IBMStreams/streamsx.jms#13]
An SPL application that consumes from a queue using JMSSource operator has the need to grab the JMS Header information such as listed in the links below and store them in tuples.

https://www.ibm.com/support/knowledgecenter/en/SSCQGF_7.2.0.3/com.ibm.IBMDI.doc_7.2.0.3/rg_conn_jms_headersandproperties.html

https://docs.oracle.com/cd/E19798-01/821-1841/bnces/index.html

Is there a way of doing so using streamsx.messaging toolkit?

**Comment by schubon** [comment]
JMSHeader values should be settable in JMSSink, too.   =>   re-open

**Comment by schubon** [comment]
Setting JMS Header values is already done by reading appropriate configuration parameters from the connection document. Values are to be set per producer and not per message (a.f.a.i.k.), so using configuration values here makes perfectly sense. I have not seen setting the prority yet, but this may be reviewed when we work on getting rid of the connection document.
