### ISSUE TITLE
Retrieve JMS Properties

### ISSUE THREAD

**Issue by AayushaY** [IBMStreams/streamsx.jms#14]
In addition to the JMS Headers, our SPL application also needs to retrieve JMS properties. Please refer to the following links for further detail.

https://www.ibm.com/support/knowledgecenter/en/SSCQGF_7.2.0.3/com.ibm.IBMDI.doc_7.2.0.3/rg_conn_jms_headersandproperties.html

https://docs.oracle.com/cd/E19798-01/821-1841/bnces/index.html

**Comment by schubon** [comment]
Hi Aayusha,

I now have the go on working on your request, but as we already planned to split the JMS functionality from the Messaging toolkit into a JMS toolkit, we will do it in this toolkit here. You will only have to switch package name and maybe some parameter names (to align the JMS operators with the majority of other operators). Until major refactoring tasks jump in, this is the same code as it was in the Messaging toolkit.

Kind regards,
Norbert

**Comment by AayushaY** [comment]
Sure, it makes sense to separate JMS from the messaging toolkit. I can take that into account and make necessary changes to my code. Do you have an ETA on when the official release would be delivered to us? I ask because our promotion to production is now dependent on it. And we are stalled until this rolls out. Also, I would really appreciate it if you could roll out the release in an official bundle that IBM periodically delivers to us and the released JMS toolkit also contains the error stream related to yet another PMR that we have with IBM. 

Thank you,
Aayusha

**Comment by schubon** [comment]
I will not make it for May, so I'm going for the next official release/fix-pack which I think is due in June. But this is not yet approved by management as far as I know.

**Comment by schubon** [comment]
Hi Aayusha,
I just committed some changes implementing the operators' access to JMS Header property values. I need to test more and want to play around with it maybe to get a feeling if this is now something useable. Current implementation follows these ideas:

Introducing a new parameter **jmsHeaderProperties** on JMSSource and JMSSink:

It specifies the mapping between JMS Header property values and Streams tuple attributes. The format of the mapping is:
`propertyName1/streamsAttributeName1/typeSpecifier1,propertyName2/streamsAttributeName2/typeSpecifier2,...`

Leading and trailing spaces are trimmed from property and attribute names.

The properties can be of the following types:

Type specifier | Java / Property type | SPL / Attribute type
------------------|---------------------------|-------------
bool           | boolean              | boolean
byte           | byte                 | int8
short          | short                | int16
int            | int                  | int32
long           | long                 | int64
float          | float                | float32
double         | double               | float64
string         | String               | rstring
object         | Object               | Object

Especially, the last line with Object types needs more testing (there's no object in SPL, probably I'll go with blob). So final implementation is still subject to change.

If type do not match the specified type, an error is logged during operator initialization.
The affected configuration will be ignored when processing messages.

Maybe you can take a look and tell me what you think?

Kind regards
Norbert

**Comment by AayushaY** [comment]
It's looking good so far, as far as code review from my side goes. Is there a way for me to download this toolkit and start testing? I don't see the committed changes as part of a release. Let me know if there's another way to do this.

Thank you,
Aayusha

**Comment by schubon** [comment]
Hi Aayusha,
you schould be able to clone the repository and in your build environment a simple 'ant clean all' should build the toolkit. Currently, I am figuring out which SPL types can be mapped into object JMS Header properties, then I wanted to provide a sample application here. Only when this is readied I wanted to make a release complete with downloadable binaries.

Kind regards
Norbert

**Comment by schubon** [comment]
Hi Aayusha,
can you play with release v1.1.0, please, and tell me, if it is usable in your use case, or if you need something else?

**Comment by AayushaY** [comment]
So if my understanding is correct, in the case that I want to access header property such as JMS_IBM_MsgType of type string. I would specify it as 
'JMS_IBM_MsgType/receivedJhpString/string' under 'propertyName1/streamsAttributeName1/typeSpecifier1' convention, correct? And if I had another one of the same type, say JMS_IBM_Format, I would specify this as well as 'JMS_IBM_Format/receivedJhpString/string' in addition to the one above to the 'jmsHeaderProperties' param of JMSSource?

**Comment by schubon** [comment]
Yes, with regards to the format, but in your example above you used 'receivedJhpString' twice. The value in the middle is the name of the attribute in the attached stream (a.k.a. tuple), so if in your example you want to store the values of properties 'JMS_IBM_MsgType' and 'JMS_IBM_Format' in one tuple, you refer to different tuple attributes by their respective names, say 'attributeNameForMsgType' and 'attributeNameForFormat'.

**Comment by AayushaY** [comment]
That sounds good, In our case, the list of properties is dynamic and we won't know what we'll be receiving. The list could expand or contract based on the sender of the message. Do correct me if I'm wrong but based on some testing I performed on the released toolkit, it appeared to me that I would have to know the names of each of the properties beforehand and include it in my code. However, our goal is to capture essentially every property that comes our way through JMSSource. Would this toolkit be able to do that?

**Comment by schubon** [comment]
Hi Aayusha,
you are correct, the current implementation requires you to know the names of the properties to access their values. Dynmamic numbers of properties with inknown names and of unknown types can not be handled in the toolkit now.

I did some experiments though (not everything tested yet, so the following insights still bear some uncertainties regarding feasability.

The JMS API provides a methods 'getPropertyNames()' and 'getObjectProperty()'. These can be used to iterate over a list of properties, thus providing the properties' names and with these a way to get an Object class representation of the property's value.

On the output tuple side we need an attribute to store all these values and a parameter to make this attribute known in the operator. The type of the attribute must be a collection, naturally, a map comes to mind. As the Object class has no unique representation within SPL, so probably blob must be used. On SPL side we will then have the type map<rstring,blob>. Inside the operator we work with java.util.Map<String,Object>.

**I have not tested yet if "java.util.Map<String,Object>" maps to "map<rstring,blob>" on SPL side, but lets assume it does for now.**

This solution means that down stream (in the responsibility of the user a.k.a. YOU) a component has to examine the attached map and correctly cast the data values from blob over Object to the real type of the value.

Does this approach meet what you want to do?

What is the maximum number of properties you expect?

**Comment by AayushaY** [comment]
Yes, this makes sense. However, is there a means by which the type of property values could be inspected on our side? We could also cast everything as string but we might receive some exceptions and I'm not sure if a "try catch exceptions" equivalent exists in SPL. Also, to answer your question regarding the maximum number of properties, we don't know the amount. The sender could be transmitting any number of properties via JMS. Is there a need for you to determine the maximum?

**Comment by schubon** [comment]
Hi Aayusha,
I discussed the map problem (or more specific the map-Object-to-blob problem) with some colleagues today (no code to tests the following has been written yet). The root cause of the problem is, that SPL does not define an appropriate type for Java's Object class type. This is why I fell back to the blob type. Streams defines a Blob interface type, so the above pair would become: Map<String,Blob>   <=>   map<rstring,blob>.
This leaves us with the challenge to map Object objects into Blob objects. Blobs being byte arrays and Objects being 'whatevers', the only way to do this is serializing the Object data into a byte array via an InputStream. This must be done for every property in the header before the map is completely filled and can be passed over to the tuple that is sent down stream.

Somewhere down stream there has to be an entity (another primitive Java operator implementing domain knowledge) that reverses that operation and that - for every property - must deserialize the blob data into an Object object and that channels the resulting object into an instanceof-cascade to create the original typed property value. If the down stream entity knows the property's names and types, you ccan spare the instanceof-cascade, but will have a property-name-cascade.

All these operations are expensive and will affect performance, which was the background of my question for the maximum number of properties you expect in a JMS message.

It feels a bit like JMS header properties are being misused to transport data in a structured way instead of the JMS message's body. I'm assuming that you have a lot of legacy systems all posting to the same message queue, but maybe you have an option to restructure the set-up?

Maybe you can inform us about your use case via the support channel and not in the open?

Kind regards
Norbert

**Comment by AayushaY** [comment]
Hi Norbert,

I can see your point of view with regards to the Serde's effect on performance. Also unfortunately, it is not entirely up to us to restructure the set-up. I could share a use case with you via an already opened PMR (Case no. TS002075742). Do take a look at it for a list of JMS header/properties we received for one of our applications. Note that it is just one use case. Others could look different. Let me know your thoughts. 

Thank you,
Aayusha

**Comment by AayushaY** [comment]
Hi Norbert,

I have been testing out the JMS toolkit that you released. I was able to get the JMS Sink operator to work and consequently populate the queues with the data in conjunction with header and properties. However, upon testing the JMS Source toolkit, I am receiving the following error: Required attribute allreceivedProperties is missing from schema tuple<map<ustring,ustring> allReceivedProperties,uint64 seqID,rstring msg>. I have looked through the sample you provided well and modeled my test application just that way. Please let me know if you know why I might be receiving this error.

**Comment by schubon** [comment]
Good Morning Aayusha,

tuple attribute names are case sensitive, so
allreceivedProperties
and
allReceivedProperties
are different variable names.

**Comment by AayushaY** [comment]
Yes, of course. Typos are the bane of a coder's existence. Thanks for pointing it out!

**Comment by AayushaY** [comment]
Hi Norbert,

This is looking great so far. I was able to extract all the received properties and this is in fact what we were looking for. So thank you so much for your helping us reach our goal. I have two questions, however. One about headers and the other about the messages on the queue. 

Firstly, I get the following result when I ingest messages that were already out there on the queues. The "msg" field is blank as you can see and does not pick up the message. Now I did change the MessageBodyData to rstring msg and I made the necessary changes in the native schema on xml as well. I am still testing this out but let me know if something comes to your mind that would resolve this. 

{allReceivedProperties={"JMS_IBM_MsgType":"8","JMS_IBM_PutApplType":"28","JMSXDeliveryCount":"1","JMS_IBM_Character_Set":"UTF-8","JMS_IBM_Format":"MQSTR   ","JMS_IBM_Encoding":"273","JMS_IBM_PutDate":"20190326","JMSXAppID":"WebSphere MQ Client for Java","JMS_IBM_PutTime":"20093023","JMSXUserID":"xyz     "},msg=""}

Secondly, would I need to specify the header attributes(listed below) in the param section of this operator to grab headers like we did in the old operator?

jmsDestinationOutAttrName : "dest" ;
jmsDeliveryModeOutAttrName : "deliveryMode" ;
jmsExpirationOutAttrName : "expiration" ;
jmsPriorityOutAttrName : "prio" ;
jmsMessageIDOutAttrName : "msgId" ;
jmsTimestampOutAttrName : "ts" ;
jmsCorrelationIDOutAttrName : "correlationId" ;
jmsReplyToOutAttrName : "replyTo" ;
jmsTypeOutAttrName : "jmsType" ;
jmsRedeliveredOutAttrName : "redelivered" ;

The grabbing of these headers and properties combined would be perfect for us as opposed to just one or the other. Let me know what you think. 

Thank you,
Aayusha

**Comment by schubon** [comment]
Hi Aayusha,

good to hear that you can extract the needed data so far.

Regarding the first question:
This sounds weird, as for the client it is irrelevant when a message has been posted, there aren't different message calls for massages of different age. But you said that you changed the the MessageBodyData. Is it possible that the messages that were already posted on the queue were using the older format?

Regarding the second question:
Surely you can grad header values and header property values in parallel on one operator.

Hope that helps.

Kind regards
Norbert

**Comment by AayushaY** [comment]
Hi Norbert,

I was doing some further testing and some questions came up. Is the new JMSSource operator expecting the messages on the queue to be in a Map before it ingests them? Can you confirm if the operator is able to ingest just a plain string from the queue. If it does, would I then have to change the Map to JSON downstream?

Thanks,
Aayusha

**Comment by AayushaY** [comment]
Correction on the last line, third word: "If it doesn't, ..."

**Comment by schubon** [comment]
Hi Aayusha,
after reading your comments and your email, I checked the code again and ran the tests for message class 'text' again. I can confirm, that the tests for TextMessages do run successfully.
As I thought you are working with MapMessages that you want to read as TextMessages, I wrote another test app, where I put MapMessages and reads TextMessages, just to check the behaviour. Which is: The JMSSource operator drops these messages because it cannot cast MapMessage to TextMessage.
So now I am confused why you still received something, after switching from MapMessage to TextMessage in your native schema. In this case here, do you control the sender, too?

Can you email me your output tuple and native schema definitions from before and after your switch to TextMessage, I think I misunderstood what you did exactly.

Kind regards
Norbert

**Comment by schubon** [comment]
Hi Aayusha,
as you made the changes as I anticipated I needed to dig deeper and found the issue. The tests that I ran were old tests that were simply checking message class text communication works, but they were not accessing header values.
The current implementation that handles text messages simply anticipates just a single String attribute in the tuple, which is not true anymore (and never should have anticipated).
I created issue #22 for this.

**WORKAROUND**:
If you can move the string message attribute in your input and output tuple definition to the first position, you will get the message payload extracted.

Kind regards
Norbert

**Comment by schubon** [comment]
After e-mail exchange with Aayusha the application she is working on is now up and running and has access to payload data, header values, and header property values. Closing this issue for now.
