### ISSUE TITLE
JMS operators do not work with IBM MQ Lite

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.jms#4]
We should either document this or document how to support it. IBM MQ Lite is how people try out IBM MQ.

**Comment by schubon** [comment]
Refering to [IBM MQ Light V1.0 simplifies development of scalable and responsive applications on premise or in the cloud](https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?infotype=AN&subtype=CA&htmlfid=897/ENUS214-390&appname=USN) and even more to this[5 Things to Know about MQ Light](https://www.ibm.com/developerworks/community/blogs/5things/entry/5_things_to_know_about_mq_light?lang=en), I came to the following conclusion:

IBM MQ Light provides an AMQP API but not a JMS API. This is simply another protocol not directly related to JMS, and thus IBM MQ Light is NOT A VALID "TARGET" for JMS operators to work with!

The request is thus obsolete/cancelled/... and I will close it now.
